workflows:
  android-release:
    name: Android Release
    instance_type: mac_mini_m2
    environment:
      groups:
        - keystore
      vars:
        CM_KEYSTORE_PATH: './android/app/my-release-key.keystore'
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'production'
          include: true
          source: true
      cancel_previous_builds: true
    scripts:
      - name: Install yarn dependencies
        script: |
          yarn
      - name: Set Android SDK location
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
      - name: Decode keystore
        script: |
          echo $CM_KEYSTORE | base64 --decode > ./android/app/my-release-key.keystore
      - name: Make gradlew executable
        script: |
          cd android
          chmod +x gradlew
      - name: Build Android release
        script: |
          cd android
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/apk/release/app-release.apk
    publishing:
      email:
        recipients:
          - sarangagunasekara20@gmail.com
